version: 0.2

phases:
  install:
    runtime-versions:
      
      nodejs: 14
  build:
    commands:
     
      - echo Building the Node code...
      - npm run test
artifacts:
  
    nodejs_artifacts:
      files:
        - index.js
        - package.json